version: "3.8"

services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app # Mount the current directory to /app in the container
    environment:
      - ENV_VAR_NAME=value # Add any environment variables your app needs
